package platform

import (
	"fmt"
	"strings"
)

// GenerateAdafruitJavaScript builds a simple MakeCode Adafruit-compatible JavaScript string from melody input.
func GenerateAdafruitJavaScript(input *ConversionInput) (string, error) {
	if input == nil || input.Melody == nil {
		return "", fmt.Errorf("conversion input is required")
	}
	if len(input.Melody.Notes) == 0 {
		return "", fmt.Errorf("melody data must contain at least one note")
	}

	var lines []string
	lines = append(lines, "// Generated by music-basicifier")
	lines = append(lines, "let melody = []")
	for _, note := range input.Melody.Notes {
		lines = append(lines, fmt.Sprintf("melody.push(%q)", note.Pitch))
	}
	lines = append(lines, "basic.forever(() => {\n  music.playMelody(melody, 120)\n})")
	return strings.Join(lines, "\n"), nil
}
