package platform

import (
	"fmt"
	"strings"
)

var adafruitNoteFrequencies = map[string]int{
	"C":  262,
	"C#": 277,
	"D":  294,
	"D#": 311,
	"E":  330,
	"F":  349,
	"F#": 370,
	"G":  392,
	"G#": 415,
	"A":  440,
	"A#": 466,
	"B":  494,
}

// GenerateAdafruitJavaScript builds a simple MakeCode Adafruit-compatible JavaScript string from melody input.
func GenerateAdafruitJavaScript(input *ConversionInput) (string, error) {
	if input == nil || input.Melody == nil {
		return "", fmt.Errorf("conversion input is required")
	}
	if len(input.Melody.Notes) == 0 {
		return "", fmt.Errorf("melody data must contain at least one note")
	}
	for i, note := range input.Melody.Notes {
		if note.Pitch == "" {
			return "", fmt.Errorf("melody note %d has empty pitch", i)
		}
		if note.Duration <= 0 {
			return "", fmt.Errorf("melody note %d has invalid duration", i)
		}
		if _, ok := adafruitNoteFrequencies[note.Pitch]; !ok {
			return "", fmt.Errorf("melody note %d has unsupported pitch %q", i, note.Pitch)
		}
	}

	var lines []string
	lines = append(lines, "// Generated by music-basicifier")
	lines = append(lines, "let tempo = 120")
	lines = append(lines, "")
	lines = append(lines, "input.buttonA.onEvent(ButtonEvent.Click, function () {")
	lines = append(lines, "    playGeneratedMelody()")
	lines = append(lines, "})")
	lines = append(lines, "")
	lines = append(lines, "function playGeneratedMelody () {")
	lines = append(lines, "    music.setTempo(tempo)")
	for _, note := range input.Melody.Notes {
		lines = append(lines, fmt.Sprintf("    music.playTone(%d, music.beat(BeatFraction.%s))", adafruitNoteFrequencies[note.Pitch], adafruitBeatFraction(note.Duration)))
	}
	lines = append(lines, "}")
	return strings.Join(lines, "\n"), nil
}

func adafruitBeatFraction(duration int) string {
	if duration <= 1 {
		return "Quarter"
	}
	if duration == 2 {
		return "Half"
	}
	return "Whole"
}
