package platform

import (
	"strings"
	"testing"
)

func TestGenerateAdafruitJavaScriptRequiresInput(t *testing.T) {
	_, err := GenerateAdafruitJavaScript(nil)
	if err == nil {
		t.Fatal("expected error when conversion input is nil")
	}
}

func TestGenerateAdafruitJavaScriptRendersNotes(t *testing.T) {
	input := &ConversionInput{Melody: &MelodyData{Notes: []MelodyNote{{Pitch: "C", Duration: 1}}}}
	program, err := GenerateAdafruitJavaScript(input)
	if err != nil {
		t.Fatalf("expected JavaScript output to be generated: %v", err)
	}
	if !strings.Contains(program, "// Generated by music-basicifier") {
		t.Fatalf("expected JavaScript output header, got %q", program)
	}
}

func TestGenerateAdafruitJavaScriptRejectsInvalidNotes(t *testing.T) {
	_, err := GenerateAdafruitJavaScript(&ConversionInput{Melody: &MelodyData{Notes: []MelodyNote{{Pitch: "", Duration: 1}}}})
	if err == nil {
		t.Fatal("expected empty pitch to fail")
	}

	_, err = GenerateAdafruitJavaScript(&ConversionInput{Melody: &MelodyData{Notes: []MelodyNote{{Pitch: "C", Duration: 0}}}})
	if err == nil {
		t.Fatal("expected invalid duration to fail")
	}
}
