package platform

import (
	"fmt"
	"strings"
)

var qbasicNoteFrequencies = map[string]int{
	"C":  262,
	"C#": 277,
	"D":  294,
	"D#": 311,
	"E":  330,
	"F":  349,
	"F#": 370,
	"G":  392,
	"G#": 415,
	"A":  440,
	"A#": 466,
	"B":  494,
}

// GenerateQBASICProgram builds a simple QBASIC program string from melody input.
func GenerateQBASICProgram(input *ConversionInput) (string, error) {
	if input == nil || input.Melody == nil {
		return "", fmt.Errorf("conversion input is required")
	}
	if len(input.Melody.Notes) == 0 {
		return "", fmt.Errorf("melody data must contain at least one note")
	}
	for i, note := range input.Melody.Notes {
		if note.Pitch == "" {
			return "", fmt.Errorf("melody note %d has empty pitch", i)
		}
		if note.Duration <= 0 {
			return "", fmt.Errorf("melody note %d has invalid duration", i)
		}
		if _, ok := qbasicNoteFrequencies[note.Pitch]; !ok {
			return "", fmt.Errorf("melody note %d has unsupported pitch %q", i, note.Pitch)
		}
	}

	var lines []string
	lines = append(lines, "10 REM Generated by music-basicifier")
	lines = append(lines, "20 CLS")
	lineNumber := 30
	for i, note := range input.Melody.Notes {
		playLength := qbasicPlayLength(note.Duration)
		soundTicks := qbasicSoundTicks(note.Duration)
		frequency := qbasicNoteFrequencies[note.Pitch]
		lines = append(lines, fmt.Sprintf("%d REM Note %d", lineNumber, i+1))
		lineNumber += 10
		lines = append(lines, fmt.Sprintf("%d PLAY \"T120 O4 L%d %s\"", lineNumber, playLength, note.Pitch))
		lineNumber += 10
		lines = append(lines, fmt.Sprintf("%d SOUND %d, %d", lineNumber, frequency, soundTicks))
		lineNumber += 10
	}
	lines = append(lines, "999 END")
	return strings.Join(lines, "\n"), nil
}

func qbasicPlayLength(duration int) int {
	if duration <= 1 {
		return 4
	}
	if duration == 2 {
		return 2
	}
	return 1
}

func qbasicSoundTicks(duration int) int {
	return duration * 4
}
