package platform

import (
	"fmt"
	"strings"
)

// GenerateQBASICProgram builds a simple QBASIC program string from melody input.
func GenerateQBASICProgram(input *ConversionInput) (string, error) {
	if input == nil || input.Melody == nil {
		return "", fmt.Errorf("conversion input is required")
	}
	if len(input.Melody.Notes) == 0 {
		return "", fmt.Errorf("melody data must contain at least one note")
	}
	for i, note := range input.Melody.Notes {
		if note.Pitch == "" {
			return "", fmt.Errorf("melody note %d has empty pitch", i)
		}
		if note.Duration <= 0 {
			return "", fmt.Errorf("melody note %d has invalid duration", i)
		}
	}

	var lines []string
	lines = append(lines, "10 REM Generated by music-basicifier")
	lines = append(lines, "20 CLS")
	for i, note := range input.Melody.Notes {
		lines = append(lines, fmt.Sprintf("%d PLAY \"%s\", %d", 10+i*10, note.Pitch, note.Duration))
	}
	lines = append(lines, "999 END")
	return strings.Join(lines, "\n"), nil
}
