package platform

import (
	"strings"
	"testing"
)

func TestGenerateQBASICProgramRequiresInput(t *testing.T) {
	_, err := GenerateQBASICProgram(nil)
	if err == nil {
		t.Fatal("expected error when conversion input is nil")
	}
}

func TestGenerateQBASICProgramRendersNotes(t *testing.T) {
	input := &ConversionInput{Melody: &MelodyData{Notes: []MelodyNote{{Pitch: "C", Duration: 1}}}}
	program, err := GenerateQBASICProgram(input)
	if err != nil {
		t.Fatalf("expected QBASIC program to be generated: %v", err)
	}
	if got := program; got == "" {
		t.Fatal("expected non-empty QBASIC program")
	}
	if want := "10 REM Generated by music-basicifier"; !strings.Contains(program, want) {
		t.Fatalf("expected program to contain %q, got %q", want, program)
	}
}

func TestGenerateQBASICProgramRejectsInvalidNotes(t *testing.T) {
	_, err := GenerateQBASICProgram(&ConversionInput{Melody: &MelodyData{Notes: []MelodyNote{{Pitch: "", Duration: 1}}}})
	if err == nil {
		t.Fatal("expected empty pitch to fail")
	}

	_, err = GenerateQBASICProgram(&ConversionInput{Melody: &MelodyData{Notes: []MelodyNote{{Pitch: "C", Duration: 0}}}})
	if err == nil {
		t.Fatal("expected invalid duration to fail")
	}
}
